config/routes.rb
Rails.application.routes.draw do
  resources :senhas
  resources :setors
  root 'index#index'
  devise_for :users

  get '/api/call', to: 'senhas#call'
  get '/api/callNext', to: 'senhas#callNext'
  get '/api/last3', to: 'senhas#last3'
  get '/api/recall/:id', to: 'senhas#recall'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/senha.rb
class Senha < ApplicationRecord
end

app/models/setor.rb
class Setor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/senhas_controller.rb
class SenhasController < ApplicationController
  before_action :set_senha, only: [:show, :edit, :update, :destroy]

  # GET /senhas
  # GET /senhas.json
  def index
    @senhas = Senha.all
  end

  # GET /senhas/1
  # GET /senhas/1.json
  def show
  end

  # GET /senhas/new
  def new
    @senha = Senha.new
  end

  # GET /senhas/1/edit
  def edit
  end

  # POST /senhas
  # POST /senhas.json
  def create
    @senha = Senha.new(senha_params)

    respond_to do |format|
      if @senha.save
        format.html { redirect_to @senha, notice: 'Senha was successfully created.' }
        format.json { render :show, status: :created, location: @senha }
      else
        format.html { render :new }
        format.json { render json: @senha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senhas/1
  # PATCH/PUT /senhas/1.json
  def update
    respond_to do |format|
      if @senha.update(senha_params)
        format.html { redirect_to @senha, notice: 'Senha was successfully updated.' }
        format.json { render :show, status: :ok, location: @senha }
      else
        format.html { render :edit }
        format.json { render json: @senha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senhas/1
  # DELETE /senhas/1.json
  def destroy
    @senha.destroy
    respond_to do |format|
      format.html { redirect_to senhas_url, notice: 'Senha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def call
    senha = Senha.where(chamado: true, dataChamado: nil).limit(1)
    for senhaChamada in senha.each
      senhaChamada.dataChamado = DateTime.now;
      senhaChamada.save;
    end
    # senha.save
    if(senhaChamada == nil)
      senha = Senha.where(rechamado: true, dataRechamado: nil, setor_id: 1).limit(1)
      for senhaChamada in senha.each
        senhaChamada.dataRechamado = DateTime.now;
        senhaChamada.save;
      end
      if(senhaChamada == nil)
        render json: {nothing: 1}
      else
        render json: senhaChamada
      end
    else
      render json: senhaChamada
    end
  end

  def callNext
    senha = Senha.where(chamado: false, dataChamado: nil, setor_id: 1).limit(1)
    for senhaChamada in senha.each
      senhaChamada.chamado = 1;
      senhaChamada.save;
    end
    # senha.save
    if(senhaChamada == nil)
      senha = Senha.where(rechamado: false, dataRechamado: nil, setor_id: 1).limit(1)
      for senhaChamada in senha.each
        senhaChamada.rechamado = 1;
        senhaChamada.save;
      end
      if(senhaChamada == nil)
        render json: {nothing: 1}
      else
        render json: senhaChamada
      end
      render json: {nothing: 1}
    else
      render json: senhaChamada
    end
  end

  def recall
    senha = Senha.where(rechamado: false, dataRechamado: nil, setor_id: 1, id: :id).limit(1)
    for senhaChamada in senha.each
      senhaChamada.rechamado = 1;
      senhaChamada.save;
    end
    if(senhaChamada == nil)
      render json: {nothing: 1}
    else
      render json: senhaChamada
    end
  end

  def last3
    render json: Senha.where(chamado: true).where.not(dataChamado: nil).order('-id').limit(3);
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_senha
      @senha = Senha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def senha_params
      params.require(:senha).permit(:senha, :dataGeracao, :chamado, :dataChamado, :rechamado, :dataRechamado, :isPrioritario, :setor_id, :usuario_id)
    end
end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
  before_action :set_setor, only: [:show, :edit, :update, :destroy]

  # GET /setors
  # GET /setors.json
  def index
    @setors = Setor.all
  end

  # GET /setors/1
  # GET /setors/1.json
  def show
  end

  # GET /setors/new
  def new
    @setor = Setor.new
  end

  # GET /setors/1/edit
  def edit
  end

  # POST /setors
  # POST /setors.json
  def create
    @setor = Setor.new(setor_params)

    respond_to do |format|
      if @setor.save
        format.html { redirect_to @setor, notice: 'Setor was successfully created.' }
        format.json { render :show, status: :created, location: @setor }
      else
        format.html { render :new }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setors/1
  # PATCH/PUT /setors/1.json
  def update
    respond_to do |format|
      if @setor.update(setor_params)
        format.html { redirect_to @setor, notice: 'Setor was successfully updated.' }
        format.json { render :show, status: :ok, location: @setor }
      else
        format.html { render :edit }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1
  # DELETE /setors/1.json
  def destroy
    @setor.destroy
    respond_to do |format|
      format.html { redirect_to setors_url, notice: 'Setor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setor
      @setor = Setor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setor_params
      params.require(:setor).permit(:nomeSetor, :letraSetor, :ultimaSenha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/senhas_helper.rb
module SenhasHelper
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/index/index.html.erb
<div class="row">
  <div class="medium-36 columns" id="senha">
    <div id="senhaAtual" class="displayNone">
      <h3>Senha Atual:</h3>
      <h1></h1>
      <h4></h4>
    </div>
    <div id="relogio">
      <h1></h1>
    </div>
  </div>
  <div class="medium-12 columns" id="senhas">
    <h4>Senhas Anteriores:</h4>
    <div></div>
    <!-- <div class="senha">
      <h3>N934</h3>
      <h5>Negociação</h5>
    </div>
    <hr/>
    <div class="senha isPrioritario">
      <h3>M933</h3>
      <h5>Secretaria</h5>
    </div>
    <hr/>
    <div class="senha">
      <h3>M932</h3>
      <h5>Secretaria</h5>
    </div> -->
  </div>
</div>
<audio id="chamada">
  <source src="chamada.ogg" type="audio/ogg">
  Seu navegador não suporta a tag audio.
</audio>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Senha</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'foundation.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'vendor/jquery', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor/foundation.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/senhas/_form.html.erb
<%= form_for(senha) do |f| %>
  <% if senha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(senha.errors.count, "error") %> prohibited this senha from being saved:</h2>

      <ul>
      <% senha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :senha, "Senha" %>
    <%= f.text_field :senha %>
  </div>

  <div class="field">
    <%= f.label :setor_id %>
    <%= f.number_field :setor_id %>
  </div>

  <div class="field">
    <%= f.label :usuario_id %>
    <%= f.number_field :usuario_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/senhas/edit.html.erb
<h1>Editing Senha</h1>

<%= render 'form', senha: @senha %>

<%= link_to 'Show', @senha %> |
<%= link_to 'Back', senhas_path %>

app/views/senhas/index.html.erb
<div class="row">
  <div class="medium-48 column">

    <p id="notice"><%= notice %></p>

    <h1>Senhas</h1>

    <table>
      <thead>
        <tr>
          <th>Senha</th>
          <th>Data de Geração</th>
          <th>Chamado?</th>
          <th>Data do Chamado</th>
          <th>Rechamado:</th>
          <th>Data do Rechamado</th>
          <th>É prioritário?</th>
          <th>Setor</th>
          <th>Usuario</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @senhas.each do |senha| %>
          <tr>
            <td><%= senha.senha %></td>
            <td><%= senha.dataGeracao %></td>
            <td><%= senha.chamado %></td>
            <td><%= senha.dataChamado %></td>
            <td><%= senha.rechamado %></td>
            <td><%= senha.dataRechamado %></td>
            <td><%= senha.isPrioritario %></td>
            <td><%= senha.setor_id %></td>
            <td><%= senha.usuario_id %></td>
            <td><%= link_to 'Mostrar', senha %></td>
            <td><%= link_to 'Editar', edit_senha_path(senha) %></td>
            <td><%= link_to 'Deletar', senha, method: :delete, data: { confirm: 'Você tem certeza disso?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nova Senha', new_senha_path %>
  </div>
</div>

app/views/senhas/new.html.erb
<h1>New Senha</h1>

<%= render 'form', senha: @senha %>

<%= link_to 'Back', senhas_path %>

app/views/senhas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Senha:</strong>
  <%= @senha.senha %>
</p>

<p>
  <strong>Datageracao:</strong>
  <%= @senha.dataGeracao %>
</p>

<p>
  <strong>Chamado:</strong>
  <%= @senha.chamado %>
</p>

<p>
  <strong>Datachamado:</strong>
  <%= @senha.dataChamado %>
</p>

<p>
  <strong>Rechamado:</strong>
  <%= @senha.rechamado %>
</p>

<p>
  <strong>Datarechamado:</strong>
  <%= @senha.dataRechamado %>
</p>

<p>
  <strong>Isprioritario:</strong>
  <%= @senha.isPrioritario %>
</p>

<p>
  <strong>Setor:</strong>
  <%= @senha.setor_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @senha.usuario_id %>
</p>

<%= link_to 'Edit', edit_senha_path(@senha) %> |
<%= link_to 'Back', senhas_path %>

app/views/setors/_form.html.erb
<%= form_for(setor) do |f| %>
  <% if setor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setor.errors.count, "error") %> prohibited this setor from being saved:</h2>

      <ul>
      <% setor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nomeSetor, 'Nome do Setor' %>
    <%= f.text_field :nomeSetor %>
  </div>

  <div class="field">
    <%= f.label :letraSetor, 'Letra' %>
    <%= f.text_field :letraSetor %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button'  %>
  </div>
<% end %>

app/views/setors/edit.html.erb
<h1>Editing Setor</h1>

<%= render 'form', setor: @setor %>

<%= link_to 'Show', @setor %> |
<%= link_to 'Back', setors_path %>

app/views/setors/index.html.erb
<div class="row">
  <div class="medium-48">
    <p id="notice"><%= notice %></p>

    <h1>Setores</h1>

    <%= link_to 'Novo Setor', new_setor_path, class: 'button' %>
    <table>
      <thead>
        <tr>
          <th>Nome do Setor</th>
          <th>Letra</th>
          <th>Ultima Senha</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @setors.each do |setor| %>
          <tr>
            <td><%= setor.nomeSetor %></td>
            <td><%= setor.letraSetor %></td>
            <td><%= setor.ultimaSenha %></td>
            <td><%= link_to 'Ver', setor %></td>
            <td><%= link_to 'Editar', edit_setor_path(setor) %></td>
            <td><%= link_to 'Excluir', setor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    </div>
</div>

app/views/setors/new.html.erb
<div class="row">
  <div class="medium-48">
    <h1>Novo Setor</h1>

    <%= render 'form', setor: @setor %>

    <%= link_to 'Voltar', setors_path, class: 'button secondary' %>
  </div>
</div>

app/views/setors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome do Setor:</strong>
  <%= @setor.nomeSetor %>
</p>

<p>
  <strong>Letra:</strong>
  <%= @setor.letraSetor %>
</p>

<p>
  <strong>Ultima Senha:</strong>
  <%= @setor.ultimaSenha %>
</p>

<%= link_to 'Editar', edit_setor_path(@setor), class: 'button' %> |
<%= link_to 'Voltar', setors_path, class: 'button secondary' %>